FROM node:22-slim AS base
WORKDIR /app

# Build stage
FROM base AS builder
COPY . .
WORKDIR /app/apps/web
RUN npm install -g pnpm@11 && \
    corepack enable pnpm && \
    pnpm install && \
    pnpm build

# Production stage
FROM base AS production
WORKDIR /app/apps/web

ENV NODE_ENV=production PORT=3000
EXPOSE 3000

COPY --from=builder /app/apps/web/package.json ./package.json
COPY --from=builder /app/apps/web/public ./public
COPY --from=builder /app/apps/web/.next ./.next

CMD ["node", "server.js"]
