FROM node:22-slim AS base
WORKDIR /app

# Build stage
FROM base AS builder
COPY . .
WORKDIR /app/apps/api
RUN npm install -g pnpm@11 && \
    corepack enable pnpm && \
    pnpm install && \
    pnpm prisma generate && \
    pnpm build

# Production stage
FROM base AS production
WORKDIR /app/apps/api

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/apps/api/package.json ./package.json
COPY --from=builder /app/apps/api/dist ./dist
COPY --from=builder /app/apps/api/prisma ./prisma

EXPOSE 3001
CMD ["node", "dist/main"]
